package com.geoquiz.app.data.local.db

import androidx.room.Database
import androidx.room.RoomDatabase

/**
 * Read-only game content (countries, answer aliases, flag colours and elements).
 *
 * Shipped prebuilt as `assets/databases/static.db`, generated by
 * `tools/data/build_static_db.py` from the exported schema of this class.
 * To change the content: regenerate the asset and bump [version]. Never add a
 * migration; the builder uses destructive fallback, so a newer asset simply
 * replaces the installed copy. Player data lives in [AppDatabase].
 */
@Database(
    entities = [
        CountryEntity::class,
        AliasEntity::class,
        CapitalAliasEntity::class,
        FlagColorEntity::class,
        FlagElementEntity::class
    ],
    version = StaticDatabase.VERSION,
    exportSchema = true
)
abstract class StaticDatabase : RoomDatabase() {
    abstract fun countryDao(): CountryDao
    abstract fun capitalAliasDao(): CapitalAliasDao
    abstract fun flagColorDao(): FlagColorDao
    abstract fun flagElementDao(): FlagElementDao

    companion object {
        const val VERSION = 1
        const val NAME = "static.db"
        const val ASSET_PATH = "databases/static.db"
    }
}
